// MatchDay Lounge — Vancouver Venue Seed Data
// Run with: npx ts-node --esm scripts/seed-vancouver.ts
// This data is used during development. In production, venues are created by owners via the Restaurant Portal.

// NOTE: This is a standalone JSON seed file. It can be imported by a future
// Firestore/Data Connect seed script, or loaded via the admin CLI.

export const VANCOUVER_VENUES = [
    {
        name: 'The Blarney Stone',
        slug: 'the-blarney-stone',
        description: 'Legendary Irish pub in the heart of Gastown. Live sports on 20+ screens, authentic pub grub, and the best pints in Vancouver.',
        address: '216 Carrall St, Vancouver, BC V6B 2J1',
        neighborhood: 'Gastown',
        city: 'Vancouver',
        province: 'BC',
        postalCode: 'V6B 2J1',
        cuisineType: 'Irish Pub',
        priceRange: 2,
        capacity: 200,
        websiteUrl: 'https://theblarneystonevancouver.com',
        phoneNumber: '604-687-4322',
        googleMapsUrl: 'https://maps.google.com/?q=The+Blarney+Stone+Vancouver',
        latitude: 49.2825,
        longitude: -123.1046,
        openingHours: JSON.stringify({ mon: '11:00-01:00', tue: '11:00-01:00', wed: '11:00-01:00', thu: '11:00-01:00', fri: '11:00-02:00', sat: '11:00-02:00', sun: '11:00-00:00' }),
        isVerified: true,
        isFanVenue: false,
        boostTier: 'STANDARD',
        promotions: [
            {
                title: 'Half-Price Pints & Wings',
                description: '$4 draft pints and $0.50 wings every weekday afternoon.',
                type: 'HAPPY_HOUR',
                dealType: 'BOTH',
                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                startTime: '14:00',
                endTime: '17:00',
                source: 'MANUAL',
            }
        ]
    },
    {
        name: 'Score on Davie',
        slug: 'score-on-davie',
        description: 'Vancouver's ultimate sports bar.Giant projectors, 40+ TVs, and the liveliest match- day atmosphere in the West End.',
        address: '1262 Davie St, Vancouver, BC V6E 1N3',
    neighborhood: 'West End',
    city: 'Vancouver',
    province: 'BC',
    postalCode: 'V6E 1N3',
    cuisineType: 'Sports Bar',
    priceRange: 2,
    capacity: 250,
    websiteUrl: 'https://scoreondavie.com',
    phoneNumber: '604-632-1646',
    googleMapsUrl: 'https://maps.google.com/?q=Score+on+Davie+Vancouver',
    latitude: 49.2780,
    longitude: -123.1332,
    openingHours: JSON.stringify({ mon: '11:00-01:00', tue: '11:00-01:00', wed: '11:00-01:00', thu: '11:00-01:00', fri: '11:00-02:00', sat: '10:00-02:00', sun: '10:00-00:00' }),
    isVerified: true,
    isFanVenue: true,
    boostTier: 'PREMIUM',
    promotions: [
        {
            title: '$6 Match Day Pints + $10 Nachos',
            description: 'Match day special — $6 pints and $10 loaded nachos on all FIFA game days.',
            type: 'MATCH_DAY_DEAL',
            dealType: 'BOTH',
            daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
            startTime: '11:00',
            endTime: '16:00',
            source: 'MANUAL',
        },
        {
            title: '$5 Draft & $7 Highballs',
            description: 'Daily happy hour on draft beer and well highballs.',
            type: 'HAPPY_HOUR',
            dealType: 'DRINKS',
            daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
            startTime: '15:00',
            endTime: '18:00',
            source: 'MANUAL',
        }
    ]
    },
{
    name: 'El Camino',
        slug: 'el-camino',
            description: 'Vibrant Mexican cantina with craft tequila cocktails, tacos, and a rooftop patio overlooking Gastown.',
                address: '300 W Pender St, Vancouver, BC V6B 1T3',
                    neighborhood: 'Gastown',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V6B 1T3',
                                    cuisineType: 'Mexican',
                                        priceRange: 2,
                                            capacity: 120,
                                                latitude: 49.2819,
                                                    longitude: -123.1076,
                                                        openingHours: JSON.stringify({ mon: '16:00-00:00', tue: '16:00-00:00', wed: '16:00-00:00', thu: '16:00-00:00', fri: '16:00-01:00', sat: '12:00-01:00', sun: '12:00-23:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'FEATURED',
                                                                        promotions: [
                                                                            {
                                                                                title: '$5 Cervezas & $7 Margaritas',
                                                                                description: 'Weekday happy hour with $5 Mexican beers and $7 house margaritas.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'DRINKS',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '15:00',
                                                                                endTime: '18:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Guilt & Co',
        slug: 'guilt-and-co',
            description: 'Underground speakeasy in Gastown with live music, craft cocktails, and a cozy basement vibe.',
                address: '1 Alexander St, Vancouver, BC V6A 1B2',
                    neighborhood: 'Gastown',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V6A 1B2',
                                    cuisineType: 'Cocktail Bar',
                                        priceRange: 3,
                                            capacity: 80,
                                                latitude: 49.2843,
                                                    longitude: -123.1050,
                                                        openingHours: JSON.stringify({ mon: 'closed', tue: '17:00-00:00', wed: '17:00-00:00', thu: '17:00-01:00', fri: '17:00-01:00', sat: '17:00-01:00', sun: '17:00-23:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$4 Cocktails Before 5 PM',
                                                                                description: 'Early bird cocktail special — $4 well cocktails from open until 5 PM.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'DRINKS',
                                                                                daysOfWeek: ['tue', 'wed', 'thu', 'fri', 'sat'],
                                                                                startTime: '17:00',
                                                                                endTime: '19:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'The Pint Public House',
        slug: 'the-pint-public-house',
            description: 'Massive 2-floor sports bar on Granville Strip with pool tables, dance floor, and wall-to-wall screens.',
                address: '455 Abbott St, Vancouver, BC V6B 2J6',
                    neighborhood: 'Downtown',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V6B 2J6',
                                    cuisineType: 'Sports Bar',
                                        priceRange: 2,
                                            capacity: 400,
                                                latitude: 49.2829,
                                                    longitude: -123.1107,
                                                        openingHours: JSON.stringify({ mon: '11:00-01:00', tue: '11:00-01:00', wed: '11:00-01:00', thu: '11:00-01:00', fri: '11:00-03:00', sat: '11:00-03:00', sun: '11:00-00:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$15 Pitchers & $1 Wings',
                                                                                description: 'Weekday special — $15 pitchers of domestic beer and $1 wings.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'BOTH',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '14:00',
                                                                                endTime: '17:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Tap & Barrel',
        slug: 'tap-and-barrel-convention',
            description: 'Waterfront taphouse with stunning views of False Creek, 60+ draft lines, and BC craft beer focus.',
                address: '1 Athletes Way, Vancouver, BC V5Y 0B1',
                    neighborhood: 'Olympic Village',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V5Y 0B1',
                                    cuisineType: 'Taphouse',
                                        priceRange: 2,
                                            capacity: 300,
                                                latitude: 49.2714,
                                                    longitude: -123.1077,
                                                        openingHours: JSON.stringify({ mon: '11:30-23:00', tue: '11:30-23:00', wed: '11:30-23:00', thu: '11:30-23:00', fri: '11:30-00:00', sat: '11:00-00:00', sun: '11:00-22:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$6 BC Craft Pints',
                                                                                description: 'Daily happy hour featuring BC craft pints at $6.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'DRINKS',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '15:00',
                                                                                endTime: '18:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Pourhouse',
        slug: 'pourhouse-vancouver',
            description: 'Rustic old-world saloon serving inventive cocktails and elevated bar bites in a reclaimed-wood interior.',
                address: '162 Water St, Vancouver, BC V6B 1B2',
                    neighborhood: 'Gastown',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V6B 1B2',
                                    cuisineType: 'Cocktail Bar',
                                        priceRange: 3,
                                            capacity: 100,
                                                latitude: 49.2840,
                                                    longitude: -123.1083,
                                                        openingHours: JSON.stringify({ mon: '17:00-01:00', tue: '17:00-01:00', wed: '17:00-01:00', thu: '17:00-01:00', fri: '17:00-02:00', sat: '12:00-02:00', sun: '12:00-00:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$8 Classic Cocktails',
                                                                                description: 'Happy hour with $8 classic cocktails — Old Fashioned, Negroni, Manhattan.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'DRINKS',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '17:00',
                                                                                endTime: '19:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Brewhall',
        slug: 'brewhall-vancouver',
            description: 'Industrial craft brewery and beer hall with 40 taps, food trucks, and communal seating at Olympic Village.',
                address: '97 E 2nd Ave, Vancouver, BC V5T 1B3',
                    neighborhood: 'Olympic Village',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V5T 1B3',
                                    cuisineType: 'Brewery',
                                        priceRange: 2,
                                            capacity: 350,
                                                latitude: 49.2694,
                                                    longitude: -123.1009,
                                                        openingHours: JSON.stringify({ mon: '11:30-23:00', tue: '11:30-23:00', wed: '11:30-23:00', thu: '11:30-00:00', fri: '11:30-01:00', sat: '11:00-01:00', sun: '11:00-22:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$2 Off All House Beers',
                                                                                description: '$2 off all house-brewed beers during happy hour.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'DRINKS',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '15:00',
                                                                                endTime: '17:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'The Cambie',
        slug: 'the-cambie',
            description: 'No-frills Gastown institution since 1987. Cheap pitchers, bar food, and the most backpacker-friendly spot in town.',
                address: '300 Cambie St, Vancouver, BC V6B 2N3',
                    neighborhood: 'Gastown',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V6B 2N3',
                                    cuisineType: 'Pub',
                                        priceRange: 1,
                                            capacity: 150,
                                                latitude: 49.2826,
                                                    longitude: -123.1085,
                                                        openingHours: JSON.stringify({ mon: '11:00-00:00', tue: '11:00-00:00', wed: '11:00-00:00', thu: '11:00-00:00', fri: '11:00-01:00', sat: '11:00-01:00', sun: '11:00-00:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$12 Pitchers All Day',
                                                                                description: 'House pitcher special — the cheapest pints in Gastown.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'DRINKS',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
                                                                                startTime: '11:00',
                                                                                endTime: '18:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Yaletown Brewing Company',
        slug: 'yaletown-brewing-company',
            description: 'Vancouver's original brewpub since 1994. House - brewed beers, solid pub food, and a sprawling patio in Yaletown.',
    address: '1111 Mainland St, Vancouver, BC V6B 2T9',
        neighborhood: 'Yaletown',
            city: 'Vancouver',
                province: 'BC',
                    postalCode: 'V6B 2T9',
                        cuisineType: 'Brewpub',
                            priceRange: 2,
                                capacity: 200,
                                    latitude: 49.2738,
                                        longitude: -123.1204,
                                            openingHours: JSON.stringify({ mon: '11:30-23:00', tue: '11:30-23:00', wed: '11:30-23:00', thu: '11:30-00:00', fri: '11:30-01:00', sat: '11:00-01:00', sun: '11:00-22:00' }),
                                                isVerified: true,
                                                    isFanVenue: false,
                                                        boostTier: 'FEATURED',
                                                            promotions: [
                                                                {
                                                                    title: '$5 House Pints & $7 Appetizers',
                                                                    description: 'Happy hour on all house-brewed pints and select appetizers.',
                                                                    type: 'HAPPY_HOUR',
                                                                    dealType: 'BOTH',
                                                                    daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                    startTime: '15:00',
                                                                    endTime: '18:00',
                                                                    source: 'MANUAL',
                                                                }
                                                            ]
},
{
    name: 'Mahony & Sons',
        slug: 'mahony-and-sons-stamps',
            description: 'Waterfront Irish pub at Stamps Landing with live Celtic music, big screens, and craft draught.',
                address: '37 Stamp\'s Landing, Vancouver, BC V5Z 4L8',
                    neighborhood: 'False Creek',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V5Z 4L8',
                                    cuisineType: 'Irish Pub',
                                        priceRange: 2,
                                            capacity: 180,
                                                latitude: 49.2700,
                                                    longitude: -123.1180,
                                                        openingHours: JSON.stringify({ mon: '11:00-00:00', tue: '11:00-00:00', wed: '11:00-00:00', thu: '11:00-00:00', fri: '11:00-01:00', sat: '10:00-01:00', sun: '10:00-00:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$5.50 Draught & $6 Appetizers',
                                                                                description: 'Daily happy hour with discounted draught and bar snacks.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'BOTH',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '15:00',
                                                                                endTime: '18:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Shark Club',
        slug: 'shark-club-vancouver',
            description: 'Upscale sports lounge at the West Georgia entertainment district. VIP booths, 70+ screens, premium cocktails.',
                address: '180 West Georgia St, Vancouver, BC V6B 4P4',
                    neighborhood: 'Downtown',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V6B 4P4',
                                    cuisineType: 'Sports Lounge',
                                        priceRange: 3,
                                            capacity: 350,
                                                latitude: 49.2789,
                                                    longitude: -123.1148,
                                                        openingHours: JSON.stringify({ mon: '11:00-01:00', tue: '11:00-01:00', wed: '11:00-01:00', thu: '11:00-01:00', fri: '11:00-02:00', sat: '11:00-02:00', sun: '11:00-00:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$7 Premium Cocktails',
                                                                                description: 'Daily happy hour with $7 premium cocktails and $5 bar bites.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'BOTH',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '15:00',
                                                                                endTime: '18:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Railway Stage & Beer Cafe',
        slug: 'railway-stage-beer-cafe',
            description: 'Historic live music venue since 1931. Now a 40-tap craft beer cafe with daily shows and late-night eats.',
                address: '579 Dunsmuir St, Vancouver, BC V6B 1Y4',
                    neighborhood: 'Downtown',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V6B 1Y4',
                                    cuisineType: 'Beer Cafe',
                                        priceRange: 2,
                                            capacity: 200,
                                                latitude: 49.2821,
                                                    longitude: -123.1142,
                                                        openingHours: JSON.stringify({ mon: '11:30-00:00', tue: '11:30-00:00', wed: '11:30-00:00', thu: '11:30-01:00', fri: '11:30-02:00', sat: '11:30-02:00', sun: '11:30-00:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$5 Local Craft Pints',
                                                                                description: 'Happy hour on local BC craft drafts.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'DRINKS',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '14:00',
                                                                                endTime: '17:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Kits Beach Boathouse',
        slug: 'kits-beach-boathouse',
            description: 'Beachfront restaurant and bar with panoramic views of English Bay, sunset cocktails, and fresh West Coast cuisine.',
                address: '1305 Arbutus St, Vancouver, BC V6J 5N2',
                    neighborhood: 'Kitsilano',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V6J 5N2',
                                    cuisineType: 'Seafood & Grill',
                                        priceRange: 3,
                                            capacity: 150,
                                                latitude: 49.2743,
                                                    longitude: -123.1520,
                                                        openingHours: JSON.stringify({ mon: '11:00-22:00', tue: '11:00-22:00', wed: '11:00-22:00', thu: '11:00-22:00', fri: '11:00-23:00', sat: '10:00-23:00', sun: '10:00-22:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$8 Sunset Cocktails',
                                                                                description: 'Sunset happy hour with $8 cocktails and $6 local beers on the patio.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'DRINKS',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '15:00',
                                                                                endTime: '17:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
{
    name: 'Townhall Public House',
        slug: 'townhall-public-house',
            description: 'Elevated neighbourhood pub in Main Street Village. Craft taps, wood-fired pizza, and a lively game-day scene.',
                address: '3340 Main St, Vancouver, BC V5V 3M7',
                    neighborhood: 'Main Street',
                        city: 'Vancouver',
                            province: 'BC',
                                postalCode: 'V5V 3M7',
                                    cuisineType: 'Gastropub',
                                        priceRange: 2,
                                            capacity: 120,
                                                latitude: 49.2564,
                                                    longitude: -123.1009,
                                                        openingHours: JSON.stringify({ mon: '11:30-00:00', tue: '11:30-00:00', wed: '11:30-00:00', thu: '11:30-00:00', fri: '11:30-01:00', sat: '10:00-01:00', sun: '10:00-00:00' }),
                                                            isVerified: true,
                                                                isFanVenue: false,
                                                                    boostTier: 'STANDARD',
                                                                        promotions: [
                                                                            {
                                                                                title: '$5 Pints & $8 Pizzas',
                                                                                description: 'Weekday happy hour — craft pints and personal pizzas.',
                                                                                type: 'HAPPY_HOUR',
                                                                                dealType: 'BOTH',
                                                                                daysOfWeek: ['mon', 'tue', 'wed', 'thu', 'fri'],
                                                                                startTime: '15:00',
                                                                                endTime: '18:00',
                                                                                source: 'MANUAL',
                                                                            }
                                                                        ]
},
]

// ── Fan Zones ──────────────────────────────────────────────────────────────
export const VANCOUVER_FAN_ZONES = [
    {
        name: 'Jack Poole Plaza Fan Zone',
        description: 'Official FIFA Fan Zone at the Vancouver Convention Centre. Giant screens, food vendors, live entertainment, and interactive fan activities.',
        city: 'Vancouver',
        address: '1055 Canada Pl, Vancouver, BC V6C 0C3',
        latitude: 49.2889,
        longitude: -123.1167,
        transitInfo: 'Waterfront Station (Canada Line + Expo Line) — 2 min walk.',
        entryReqs: 'Free entry. Bags checked at gate. No alcohol from outside.',
    },
    {
        name: 'Concord Pacific Fan Park',
        description: 'Waterfront fan gathering spot at the Concord Pacific lands. Pre-match entertainment, local food trucks, and a festive atmosphere.',
        city: 'Vancouver',
        address: '88 Pacific Blvd, Vancouver, BC V6Z 2S9',
        latitude: 49.2726,
        longitude: -123.1116,
        transitInfo: 'Yaletown–Roundhouse Station (Canada Line) — 5 min walk.',
        entryReqs: 'Free entry. Family-friendly area available.',
    },
]

// ── Fixtures (sample) ──────────────────────────────────────────────────────
export const SAMPLE_FIXTURES = [
    {
        id: 'wc2026-grpA-01',
        homeTeam: '🇨🇦 Canada',
        awayTeam: '🇲🇦 Morocco',
        competition: 'FIFA World Cup 2026',
        kickoffAt: '2026-06-11T19:00:00Z',
        status: 'SCHEDULED',
        venue: 'BC Place',
        city: 'Vancouver',
    },
    {
        id: 'wc2026-grpB-01',
        homeTeam: '🇧🇷 Brazil',
        awayTeam: '🇲🇽 Mexico',
        competition: 'FIFA World Cup 2026',
        kickoffAt: '2026-06-12T21:00:00Z',
        status: 'SCHEDULED',
        venue: 'BC Place',
        city: 'Vancouver',
    },
    {
        id: 'wc2026-grpC-01',
        homeTeam: '🇦🇷 Argentina',
        awayTeam: '🇯🇵 Japan',
        competition: 'FIFA World Cup 2026',
        kickoffAt: '2026-06-13T19:00:00Z',
        status: 'SCHEDULED',
        venue: 'BMO Field',
        city: 'Toronto',
    },
    {
        id: 'wc2026-grpD-01',
        homeTeam: '🇩🇪 Germany',
        awayTeam: '🇦🇺 Australia',
        competition: 'FIFA World Cup 2026',
        kickoffAt: '2026-06-14T16:00:00Z',
        status: 'SCHEDULED',
        venue: 'BC Place',
        city: 'Vancouver',
    },
    {
        id: 'wc2026-grpE-01',
        homeTeam: '🇵🇹 Portugal',
        awayTeam: '🇳🇬 Nigeria',
        competition: 'FIFA World Cup 2026',
        kickoffAt: '2026-06-14T19:00:00Z',
        status: 'SCHEDULED',
        venue: 'BMO Field',
        city: 'Toronto',
    },
]
